# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8ae1296345d87830d8f8384001ecb1be98635073b2f74fc18fe95b44da9467367dcae6505cb83815dbce7ac1fdae5408a5e5e7096c9eca88e4e3076fa00b401

test:
  secret_key_base: 8fbf38c798bc361a735dc6ba57bde7117f74f6efc36b2ebc02316e3d363b8c6d0cc969526db9f26b3b1795e2787f6b0692eda180f7c3565607f92ed39d6f2dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
